# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ef79fa639f169a962270bcfc833a2e1e26448003aef7330fdd693f7ed2a2a6bf5c7ea4862f8108fcabfdca6e713d74db11b9ee777af31a92a75a58b1498483a

test:
  secret_key_base: a399fefd9d23e58e003b7c94fbe90c169286dd1ecf7854b3cc67733d3a7ca12cdd97eb8a27d05a7ccefffe7db524a025665544f364b5c7b5bd4637d202d53f0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
