# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9923cbb53d605183d1e2a601eef3153a2ac64d5f3223684174f7bc3a71d7a72ae5f1481939b96db1647f93165815c13553be9ba79149c11b2ce622bc543fee27

test:
  secret_key_base: 8ed73ed8b35a6a234626cc3f001bd9bb1e0a19eef5b59e61409f270a8876917df1233d736b624a23df608ec78721dd8dcc3f82d7d5f67ce3937572d273140b6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
